# yaml-language-server: $schema=https://unpkg.com/@sveltia/cms/schema/sveltia-cms.json

backend:
  name: github
  repo: johnmillstead/paraclete

media_folder: /public/media
public_folder: /media

collections:
  - name: posts
    label: Posts
    label_singular: Post
    folder: /content/posts
    fields:
      - { label: Title, name: title, widget: string }
      - { label: Date, name: date, widget: datetime, type: date }
      - { label: Body, name: body, widget: richtext }

  - name: authors
    label: Authors
    label_singular: Author
    folder: /content/authors
    fields:
      - { label: Title, name: title, widget: string }
      - { label: Body, name: body, widget: richtext }

  - name: ministries
    label: Ministries
    label_singular: Ministry
    folder: /content/ministries
    fields:
      - { label: Title, name: title, widget: string }
      - { label: Body, name: body, widget: richtext }

  - name: staff
    label: Staff
    label_singular: Staff Member
    folder: /content/staff
    fields:
      - { label: Title, name: title, widget: string }
      - { label: Body, name: body, widget: richtext }

  - name: board
    label: Board
    label_singular: Board Member
    folder: /content/board
    fields:
      - { label: Title, name: title, widget: string }
      - { label: Body, name: body, widget: richtext }

  - name: projects
    label: Projects
    label_singular: Project
    folder: /content/projects
    fields:
      - { label: Title, name: title, widget: string }
      - { label: Body, name: body, widget: richtext }

  - name: resources
    label: Resources
    label_singular: Resource
    folder: /content/resources
    fields:
      - { label: Title, name: title, widget: string }
      - { label: Body, name: body, widget: richtext }
